package de.fuberlin.wiwiss.d2rq.map;

import org.apache.jena.rdf.model.Resource;

import java.util.stream.Stream;

/**
 * Created by @ssz on 26.09.2018.
 *
 * @see <a href='http://d2rq.org/d2rq-language#classmap'>5. Creating RDF resources (d2rq:ClassMap)</a>
 */
public interface ClassMap extends MapObject,
        HasDatabase<ClassMap>, HasURI<ClassMap>, HasSQL<ClassMap>, HasUnclassified<ClassMap>, HasProperties<ClassMap> {

    /**
     * Sets an RDF-S or OWL class for the predicate {@code d2rq:class}.
     * All resources generated by this ClassMap are instances of this class.
     *
     * @param clazz {@link Resource}, not {@code null}
     * @return this instance
     */
    ClassMap addClass(Resource clazz);

    /**
     * Lists all resources for the {@code d2rq:class} predicate.
     *
     * @return Stream of {@link Resource}s
     */
    Stream<Resource> listClasses();

    /**
     * Sets {@code d2rq:containsDuplicates} boolean literal.
     * Must be specified if a class map uses information from tables that are not fully normalized.
     * If the {@code d2rq:containsDuplicates} property value is set to {@code true},
     * then D2RQ adds a {@code DISTINCT} clause to all queries using this classMap.
     * {@code false} is the default value, which doesn't have to be explicitly declared.
     * Adding this property to class maps based on normalized database tables degrades query performance,
     * but doesn't affect query results.
     *
     * @param b boolean
     * @return this instance to allow cascading calls
     * @see #containsDuplicates()
     */
    ClassMap setContainsDuplicates(boolean b);

    /**
     * Answers if the {@code d2rq:containsDuplicates} is set to {@code true}.
     *
     * @return boolean
     * @see #setContainsDuplicates(boolean)
     */
    boolean containsDuplicates();

    /**
     * Produces a blank node as {@code d2rq:constantValue}.
     *
     * @return this object to allow cascading calls
     * @see HasURI#setConstantValue(String)
     */
    ClassMap setConstantValue();

    /**
     * Adds the specified {@link PropertyBridge d2rq:PropertyBridge} into this class-map.
     * This methods creates the {@code d2rq:belongsToClassMap} relation for this class-map and the given property-bridge
     * and copiers all the content of the property-bridge if it is not already in the graph.
     *
     * @param p {@link PropertyBridge} not {@code null}
     * @return this instance
     */
    ClassMap addPropertyBridge(PropertyBridge p);

    /**
     * Lists all {@link PropertyBridge d2rq:PropertyBridge},
     * that are attached to this class-map using the {@code d2rq:belongsToClassMap} relation.
     *
     * @return Stream of {@link PropertyBridge}s
     */
    Stream<PropertyBridge> listPropertyBridges();


    default ClassMap addClass(String uri) {
        return addClass(getMapping().asModel().createResource(uri));
    }

}
