package de.fuberlin.wiwiss.d2rq.vocab;

import org.apache.jena.rdf.model.Property;
import org.apache.jena.rdf.model.Resource;
import org.apache.jena.rdf.model.ResourceFactory;

/**
 * An addition to the {@link D2RQ standard D2RQ} vocabulary.
 * Created by @ssz on 13.10.2018.
 */
@SuppressWarnings("WeakerAccess")
public class AVC {
    public static final String BASE_URI = "http://avc.ru/d2rq";
    public static final String NS = BASE_URI + "#";

    public static String getURI() {
        return BASE_URI + "/";
    }

    /**
     * To indicate that something in the auto-generated mapping is suspicious.
     */
    public static final Property warning = property("warning");

    /**
     * An addition configuration property to control building OWL2 Schema from a D2RQ Mapping.
     * If turn on, then mapping should contains also instructions
     * ({@link de.fuberlin.wiwiss.d2rq.map.ClassMap}s and {@link de.fuberlin.wiwiss.d2rq.map.PropertyBridge}s)
     * to generate some OWL declaration statements
     * (e.g. for {@link ru.avicomp.ontapi.jena.vocabulary.OWL#NamedIndividual owl:NamedIndividual}).
     * TODO: should be b-node
     *
     * @see D2RQ#Configuration
     */
    public static final Property controlOWL = property("controlOWL");

    /**
     * An addition configuration property to control
     * {@link ru.avicomp.ontapi.jena.vocabulary.OWL#NamedIndividual owl:NamedIndividual} declarations,
     * generated by the mapping for a concrete class-map.
     * If it is on, then each named instance will have that declaration, as it is recommended by the OWL2 spec.
     *
     * @see AVC#controlOWL
     * @see D2RQ#Configuration
     */
    public static final Property generateNamedIndividuals = property("generateNamedIndividuals");

    /**
     * An addition configuration property to turn on/off a cache for D2RQ Data Graph.
     * The right part of the statement with this predicate must be {@code xsd:boolean} literal.
     * This option is experimental and by default it is absent in a Mapping graph
     * (which means that there is no caching for data graph).
     * TODO: should be b-node
     *
     * @see D2RQ#Configuration
     */
    public static final Property withCache = property("withCache");

    /**
     * A cache additional property to set up max absolute cache length limit expressed in a conventional unit,
     * that is approximately equaled to the 16 bit (char size).
     * The right part of the statement with this predicate
     * must be {@code xsd:integer} literal, with positive int as value.
     *
     * @see AVC#withCache
     * @see D2RQ#Configuration
     * @see de.fuberlin.wiwiss.d2rq.jena.CachingGraph
     */
    public static final Property cacheLengthLimit = property("cacheLengthLimit");

    /**
     * A cache additional property to set up max cache keys size.
     * The right part of the statement with this predicate
     * must be {@code xsd:integer} literal, with positive int as value.
     *
     * @see AVC#withCache
     * @see D2RQ#Configuration
     * @see de.fuberlin.wiwiss.d2rq.jena.CachingGraph
     */
    public static final Property cacheMaxSize = property("maxKeysSize");

    /**
     * Property-marker to indicate that a related
     * {@link de.fuberlin.wiwiss.d2rq.map.PropertyBridge PropertyBridge}
     * or {@link de.fuberlin.wiwiss.d2rq.map.ClassMap ClassMap} is dynamically generated
     * by mapping itself while compiling.
     */
    public static final Property autoGenerated = property("autoGenerated");

    /**
     * Makes a fresh uri-resource with local name {@code Unknown}-{@code suffix},
     * where {@code suffix} is a specified string.
     * Used to generate missed classes if the corresponding {@link de.fuberlin.wiwiss.d2rq.map.ClassMap}
     * is an anonymous resource.
     *
     * @param suffix String, not {@code null}
     * @return {@link Resource}
     */
    public static Resource UnknownClass(String suffix) {
        return resource("Unknown-" + suffix);
    }

    protected static Resource resource(String local) {
        return ResourceFactory.createResource(NS + local);
    }

    protected static Property property(String local) {
        return ResourceFactory.createProperty(NS + local);
    }

}
